name: Deploy on EC2

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env  
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t muhammadhuzaifa8/Todo-List-nodejs .  
      - name: Publish image to docker hub
        run: docker push muhammadhuzaifa8/Todo-List-nodejs

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull muhammadhuzaifa8/Todo-List-nodejs:latest
      - name: Delete old container
        run: docker rm -f tododlist
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name todolist muhammadhuzaifa8/Todo-List-nodejs
